[About]
Author = ARM
Discord = https://discord.gg/rtBfy5AWSE
Channel = https://youtube.com/@arm_chxd
Version = 7.3.1 PBLC
PresetBy = HAMA

; See at the bottom for more information!
; Use this as a base for your new preset or whatever you like. Don't ping me for random stuff on discord ~ARM

[HUD_PlayerInfo]
ForceDrawing = 1        ; Forced the HUD to always draw. e.g. billiards mini game where player Info is disabled.

[HUD_BarArmor]
AlwaysShow = 0          ; 0 - Vanilla. 1 - Always draw
BorderMult = 1.500000
BorderSide = 30         ; left = 2. top = 4. bottom = 8. right = 16. {2 + 4 = draw left and top. and so on}
Color = 225 225 225 255
ConstWidth = 1          ; 0 - Do longer bar. 1 - Don't do longer bar
DrawMode = 0            ; 0 - Draw normally. 1- Draw behind blips(GTA V stuff)
FlashItem = 1
Percent = 0             ; Show percentage inside the bar
PosX = 96.080000
PosY = 11.0000000
SizeX = 8.1000000
SizeY = 1.2000000
Vertical = 0            ; 0 Horizontal. 1 - Vertical

[HUD_BarBreath]
AlwaysShow = 0          ; 0 - Vanilla. 1 - Always draw
BorderMult = 1.500000   ; Multiplier for the bar border
BorderSide = 30         ; left = 2. top = 4. bottom = 8. right = 16. {2 + 4 = draw left and top. and so on}
Color = 137 162 192 255
DrawMode = 0            ; 0 - Draw normally. 1- Draw behind blips(GTA V stuff)
FlashItem = 1
Percent = 0             ; Show percentage inside the bar
PosX = 96.080000
PosY = 13.8000000
SizeX = 8.1000000
SizeY = 1.1000000
Vertical = 0            ; 0 Horizontal. 1 - Vertical

[HUD_BarHealth]
AlwaysShow = 0          ; 0 - Vanilla. 1 - Always draw
BorderMult = 1.500000   ; Multiplier for the bar border
BorderSide = 30         ; left = 2. top = 4. bottom = 8. right = 16. {2 + 4 = draw left and top. and so on}
Color = 180 25 29 255
ConstWidth = 0          ; 0 - Do longer bar. 1 - Don't do longer bar
DrawMode = 0            ; 0 - Draw normally. 1- Draw behind blips(GTA V stuff)
FlashItem = 1
PCBehaviour = 1         ; Move the bar down when the bar become longer. Affecting the star, money, armor bar and breath bar.
Percent = 0             ; Show percentage inside the bar
PosX = 96.080000
PosY = 16.6000000
SizeX = 14.260000
SizeY = 1.2000000
Vertical = 0             ; 0 Horizontal. 1 - Vertical

[HUD_Ammo]
DisplayAbove9999 = 0    ; Display the ammo counter above 9999
Format = %d-%d
BGColor = 0 0 0 0
Color = 172 203 241 255
CalcWeaponRect = 0      ; Take the Weapon Icon size into account (vanilla like)
Proportional = 0
FontStyle = 6
Orientation = 0
FontEdge = 1
AnimatedMult = 1.000000 ; Animation when the count is changing (1.0 no anim).
PosX = 84.200000
PosY = 15.400000
SizeX = 0.2100000
SizeY = 0.560000

[HUD_AreaName]
BGColor = 0 0 0 0
Proportional = 1
FontStyle = 4
Orientation = 2
FontEdge = 1
PosX = 96.500000
PosY = 93.000000

[HUD_Clock]
Format = %02d:%02d
BGColor = 0 0 0 0
Color = 225 225 225 255
Proportional = 0
Orientation = 2
FontStyle = 5
FontEdge = 2
PosX = 96.180000
PosY = 4.700000
SizeX = 0.468000
SizeY = 1.36900050000

[HUD_Money]
Format = $%08d
ColorMinus = 180 25 29 255
ColorPlus = 54 104 44 255
BGColor = 0 0 0 0
FontStyle = 5
Proportional = 0
Orientation = 2
FontEdge = 2
DropShadow = 1
PosX = 96.200000
PosY = 19.000000
SizeX = 0.47000
SizeY = 1.30000

[HUD_MoneyChange]
Enable = 0
Proportional = 1
FontEdge = 1
Orientation = 0
FontStyle = 5
DropShadow = 0
DisplayTime = 3000
AnimSpeed = 0.500000
AnimStart = 0.000000
ColorMinus = 180 25 29 255
ColorPlus = 54 104 44 255
BGColor = 0 0 0 255
PosX = 50.000000
PosY = 50.000000
SizeX = 0.470000
SizeY = 1.100000

[HUD_Radar]
PlayerPosX = 0.000000
PlayerPosY = 0.000000
Range = 0.000000      ; Radar zoom
PosX = 7.100000
PosY = 85.000000
SizeX = 4.900000
SizeY = 10.700000

[HUD_Radio]
EnableIcon = 0        ; Use texture instead of text
BGColor = 0 0 0 255
Proportional = 1
FontStyle = 2
Orientation = 0
FontEdge = 1
PosX = 50.000000
PosY = 5.000000
SizeX = 0.300000
SizeY = 1.100000

[HUD_Subtitles]
FontStyle = 1
Proportional = 1
Orientation = 0
FontEdge = 1
DropShadow = 2
PosX = 49.970000
PosY = 94.000000
SizeX = 0.348000
SizeY = 1.000000

[HUD_VehName]
BGColor = 0 0 0 0
Proportional = 1
FontStyle = 2
Orientation = 2
FontEdge = 1
PosX = 96.500000
PosY = 93.000000

[HUD_WantedStar]
Color = 144 98 16 255
BGColor = 0 0 0 255
AlwaysShowShadow = 0
Icon = ]              ; Icon of the star
FontStyle = 4
FontEdge = 1
Orientation = 2
Proportional = 0
Padding = 0.122440    ; Distance between star
PosX = 95.76000
PosY = 25.00000
SizeX = 0.481000
SizeY = 1.390000
Vertical = 0

[HUD_WeaponIcon]
DrawBehind = 0      ; Draw behind the other HUD elements (bars, money, etc)
PosX = 84.300000
PosY = 11.7000000
SizeX = 3.100000
SizeY = 7.700000

; PosX = Horizontal position on screen. 0.0 left. 100.0 right
; PosY = Vertical position on screen. 0.0 top. 100.0 bottom 
; SizeX = Horizontal size
; SizeY = Vertical size

; FontStyle
; 0 - Gothic. 1 - Subtitles. 2 - Menu. 3 - Pricedown
; Orientation
; 0 - Centered. 1 - Aligned left. 2 - Aligned right