; ClassicPostFX Beta

[PostEffects]

SpeedFX = 1           ; enable or disable the blur effect when driving or activating nitro effect.

# this heathaze effect is still on test, and its not working on special effects(jetpack, hydra, fire).
HeatHaze = 0

# HeatHaze setting
heathazeIntensityMult = 0.6        ; (default: 1.0) multiplier of intensity effect of heathaze.

# UnderWaterRipple settings
UnderWaterRipple = 1      ; enable or disable UnderWaterRipple effect.
underWaterRippleSpeed = 0.0015        ; (default: 0.0015)
underWaterRippleFrequency = 0.04     ; (default: 0.04)

# Radiosity settings
doRadiosity = 0                       ; enable or disable Radiosity.
Radiosity = 0                        ; Radiosity implementation.
                                                ; values: (1 = PS2 || 2 = Shader).
radiosityFilterPasses = 2
radiosityRenderPasses = 1
radiosityIntensity = 35

# others
grain = 1                       ; enable or disable grain effect for infrared, night vision and rain.
grainFilter = 2                 ; grain filter implementation.
                                           ; values: (1 = PS2 || 2 = PC).


[Misc]
Moonphases = 1
