; fastman92limitAdjuster_GTASA.ini
; ARM

; Important information: do not set limits to very high values like 9999999!
; Each increase of limit is usually correlated with an increase of memory being used.
; Some understanding is required to set up the limits.

[DYNAMIC LIMITS]
; ColModels (10150)
; Number of different collisions that can be loaded.
ColModels = 20000

; VehicleStructs (50)
; Max number of vehicles with different IDs loaded.
VehicleStructs = 256

; rwObjectInstances (1500)
rwObjectInstances = 20000

; Matrices (900)
Matrices = 2000

; PtrNode Singles (75000)
PtrNode Singles = 300000

; PtrNode Doubles (6000)
PtrNode Doubles = 500000

; EntryInfoNodes (500)
EntryInfoNodes = 20000

[IPL]
; Buildings (14000)
Buildings = 40000

; Dummies (3500)
Dummies = 20000

; Entity index array (40)
#Entity index array = 512

; Entry exits (455)
Entry exits = 600

[IDE LIMITS]
; IDE Objects Type 1 (14000)
IDE Objects Type 1 = 40000

; IDE Objects Type 2 (70)
IDE Objects Type 2 = 1500

; Timed Objects (169)
Timed Objects = 300

; Hier Objects (92)
; Clump models
Hier Objects = 180

; Vehicle Models (212)
Vehicle Models = 1000

; Ped Models (278)
Ped Models = 800

; Weapon Models (51)
#Weapon Models = 51

; 2DFX Effects (100)
#2DFX Effects = 100

[MAP LIMITS]
; Apply paths limit patch (0)
#Apply paths limit patch = 1

; Enable path debugging (0)
; Make sure to increase 'OTHER LIMITS -> Coronas', because the path debugging registers a large number of coronas to be rendered.
#Enable path debugging = 1

; Paths map size (6000)
; This option requires a new set of files if map size is changed!!!
#Paths map size = 6000

; Water map size (6000)
#Water map size = 6000

; Renderware world map size (20000)
Renderware world map size = 120000

; World map size (6000)
World map size = 24000

; World sector size (50)
World sector size = 200

; World LOD sector size (200)
World LOD sector size = 800

[IMG LIMITS]
; Max number of IMG archives (8)
#Max number of IMG archives = 4

[WATER LIMITS]
; Water triangles (6)
Water triangles = 14

; Water quads (301)
Water quads = 700

; Water quads and triangles list (701)
Water quads and triangles list = 1200

; Water vertices (1021)
Water vertices = 1400

; Blocks to be rendered outside world (70)
#Blocks to be rendered outside world = 69

[STREAMING]
; Memory available (50)
#Memory available = 512

; Max number of stream handles (32)
#Max number of stream handles = 2048

; Number of requested models above which the game considers loading very busy (5)
#Number of requested models above which the game considers loading very busy = 5

; Minimum number of iterations in LoadAllRequestedModels (10)
#Minimum number of iterations in LoadAllRequestedModels = 10

[RENDERER LIMITS]
; Invisible entity pointers (150)
#Invisible entity pointers = 300

; Visible super LOD pointers (50)
#Visible super LOD pointers = 500

; Visible LOD pointers (1000)
Visible LOD pointers = 4000

; Visible entity pointers (1000)
Visible entity pointers = 4000

[ID LIMITS]
; Apply ID limit patch (0)
Apply ID limit patch = 1

; FILE_TYPE_DFF (20000)
#FILE_TYPE_DFF = 24000

; FILE_TYPE_TXD (5000)
#FILE_TYPE_TXD = 5000

; FILE_TYPE_COL (255)
FILE_TYPE_COL = 500

; FILE_TYPE_IFP (180)
FILE_TYPE_IFP = 300

; FILE_TYPE_RRR (475)
FILE_TYPE_RRR = 500

; Count of killable model IDs (800)
; In game there's an array CDarkel::RegisteredKills and it stores the number of registered kills for model IDs.
; Model IDs that may be killed are vehicles/peds.
; Default value of 800, means that 0-799 is valid ID for ped/vehicle.
; 
; As such, this value will affect the max possible ID for ped/vehicle.
Count of killable model IDs = 20000

[HANDLING.CFG LIMITS]
; Apply handling.cfg patch (0)
Apply handling.cfg patch = 1

; Number of standard lines (210)
Number of standard lines = 1000

; Number of bike lines (13)
Number of bike lines = 50

; Number of flying lines (24)
Number of flying lines = 80

; Number of boat lines (12)
Number of boat lines = 50

; Number of animation group lines (30)
Number of animation group lines = 50

[SCM LIMITS]
; Max size of MAIN segment (270000)
; Altering this limit can produce different savefiles that can't be loaded if value of this limit is different.
#Max size of MAIN segment = 270000

; Max mission size (69000)
; Altering this limit can produce different savefiles that can't be loaded if value of this limit is different.
#Max mission size = 69000

; Running scripts (96)
; Altering this limit can produce different savefiles that can't be loaded if value of this limit is different.
Running scripts = 2000

; Mission cleanup (75)
#Mission cleanup = 127

; Max number of used objects (395)
Max number of used objects = 600

; Switch jump table cases (75)
#Switch jump table cases = 200

[OTHER LIMITS]
; Coronas (64)
#Coronas = 1500

; Collision size (32768)
#Collision size = 65536

; Object info entries (160)
; Max number of object.dat entries.
; 5 first entries of array are reserved for hardcoded purpose.
Object info entries = 5000

; References (3000)
#References = 3000

[ROADBLOCK LIMITS]
; Apply roadblox.dat better loader (0)
; Make it possible to use a roadblox.dat of variable size.
Apply roadblox.dat better loader = 1

[SPECIAL]
; Make save of variable size (0)
#Make save of variable size = 1

; Fix keyboard making bad mouse movement (0)
Fix keyboard making bad mouse movement = 1

; Fix cheats typed by keyboard not working (0)
Fix cheats typed by keyboard not working = 1

; Alter file loading order (1)
; Alters the file loading loading.
; Files from game root directory will take a precedence over files from APK archive.
; Useful to edit handling.cfg for example.
Alter file loading order = 1

; Remove LOD DFF requirement to hold native data (1)
Remove LOD DFF requirement to hold native data = 1

; Fix crashes on newer systems (1)
Fix crashes on newer systems = 1

; Disable CINFO.BIN and MINFO.BIN loading (1)
Disable CINFO.BIN and MINFO.BIN loading = 1

[ADDONS]
; Enable vehicle audio loader (0)
Enable vehicle audio loader = 1

[MAIN]
; author (fastman92)
author = fastman92

; Disable FLA loading text (0)
Disable FLA loading text = 1

; Register global exception handler (1)
; Crash exception handler
; You should leave it enabled or there will be no crash log.
; Please don't disable it unless you have a good reason.
Register global exception handler = 0
; Reason: we use AML Crashlog that has more detailed information about the crash and plugins loaded.

; Use a different INI ()
#Use a different INI = 